const db = require('./models');

let unit5StartingCheck = 333;

db.transaction.bulkCreate([
    {
        date: "01/10/2016",
        amount: 445,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "02/10/2016",
        amount: 445,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "03/10/2016",
        amount: 445,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "04/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "06/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "07/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "08/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "09/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "10/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "11/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "12/10/2016",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "01/10/2017",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "02/10/2017",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "03/10/2017",
        amount: 470,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "04/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "06/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "07/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "08/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "09/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "10/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "11/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "12/10/2017",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "01/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "02/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "03/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "04/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "06/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "08/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "08/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "09/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "10/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "11/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "12/10/2018",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "01/10/2019",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "02/10/2019",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "03/10/2019",
        amount: 515,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "04/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "06/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "07/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "08/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "09/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "10/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "11/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "12/10/2019",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "01/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "02/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "03/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "05/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    },    {
        date: "06/10/2020",
        amount: 570,
        checkNumber: unit5StartingCheck++,
        category: "dues",
        shareholderId: 25
    }    
])
.then(result => {
    console.log("lots of transactions added successfully");
})
.catch(error => {
    console.log(`Error seeding transactions: ${error}`);
})